### PR TITLE
Update PDF highlights.md

### PR DESCRIPTION
**Pull request by hmijail**
Add a warning about PDFs not being removed automatically.

### CODE REVIEW

**Review by cnrpman — APPROVED** [review]
LGTM

**Comment by cnrpman** [comment]
Hi. Can you open a PR in the Logseq repo?

**Comment by cnrpman** [comment]
Hi. Can you open a PR in logseq/doc ? https://github.com/logseq/docs/compare

**Comment by hmijail** [comment]
Done: https://github.com/logseq/docs/pull/110

Sorry for the mess, not sure how this got created like this.

**Pull request closed without merging**
